const statusReasons = {
  0: "Registered",
  1: "Unknown",
  6: "ConnectivityError",
  8: "DeviceInitiatedReset",
  9: "CallManagerReset",
  10: "DeviceUnregistered",
  11: "MalformedRegisterMsg",
  12: "SCCPDeviceThrottling",
  13: "KeepAliveTimeout",
  14: "ConfigurationMismatch",
  15: "CallManagerRestart",
  16: "DuplicateRegistration",
  17: "CallManagerApplyConfig",
  18: "DeviceNoResponse",
  19: "EMLoginLogout",
  20: "EMCCLoginLogout",
  25: "RegistrationSequenceError",
  26: "InvalidCapabilities",
  28: "FallbackInitiated",
  29: "DeviceSwitch",
  30: "DeviceWipe",
  31: "DeviceForcedReset",
  33: "LowBattery",
  34: "ManualPowerOff",
};

module.exports = statusReasons;
